

spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: locahost
    port: 6379
  profiles: 
    active: local 
  jpa:
    hibernate:
      ddl-auto: create
    properties: 
      hibernate: 
        show_sql: true
        format_sql: true
        new_generator_mappings: true
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 884915953449-qeufdpllfe4tml09k4s8lk51im7913fl.apps.googleusercontent.com
            client-secret: K8-0YN-mkx3PiVOzIdSwvwMT
          facebook:
            client-id: 2424884084415109
            client-secret: 3c29f4d653ee155a9d0e3d17b247dc55


            
custom: 
  oauth2: 
    kakao: 
      client-id: abbb42f618313a2f16277a0e86ccbd68
    naver: 
      client-id: RXvwZFnYRD6v61LPJpRd
      client-pw: 8O3ggp6r5p