

spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  profiles: 
    active: local 
  jpa:
    hibernate:
      ddl-auto: create
    properties: 
      hibernate: 
        show_sql: true
        format_sql: true
        new_generator_mappings: true
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1
            client-secret: 1
          facebook:
            client-id: 1
            client-secret: 1
  servlet: 
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 115MB


file:
  image-upload-root-directory: static/images/
  doc-upload-root-directory: static/docs/
    
#
#logging: 
#  level: 
#    root: warn
#  file: 
#    path: 
    
                
custom: 
  oauth2: 
    kakao: 
      client-id: 1
    naver: 
      client-id: 1
      client-pw: 1
