

spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: locahost
    port: 6379
  profiles: 
    active: local 
  jpa:
    hibernate:
      ddl-auto: create
    properties: 
      hibernate: 
        show_sql: true
        format_sql: true
        new_generator_mappings: true
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1
            client-secret: 1
          facebook:
            client-id: 1
            client-secret: 1


            
custom: 
  oauth2: 
    kakao: 
      client-id: 1
    naver: 
      client-id: 1
      client-pw: 1
